import type { Metadata, Viewport } from "next";
import Root from "@/components/Root";

import "@fortawesome/fontawesome-svg-core/styles.css";
import "@xterm/xterm/css/xterm.css";
import "./globals.css";
import "flexlayout-react/style/light.css";

export const metadata: Metadata = {
  title: "NPC CLI",
  // description: "Generated by create next app",
};

// fix xterm mobile scrolling with keyboard open (Chrome)
// <meta name="viewport" content="width=device-width, interactive-widget=resizes-content"></meta>
export const viewport: Viewport = {
  width: 'device-width',
  interactiveWidget: 'resizes-content',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      // className="dark"
    >
      <head>
        {/* ... */}
      </head>
      <body className="bg-white dark:bg-neutral-800">
        <Root>
          {children}
        </Root>
      </body>
    </html>
  );
}
