import type { Metadata, Viewport } from "next";
import Root from "@/components/Root";

import "@fortawesome/fontawesome-svg-core/styles.css";
import "@xterm/xterm/css/xterm.css";
import "./globals.css";
import "flexlayout-react/style/light.css";

export const metadata: Metadata = {
  title: "NPC CLI",
  // description: "Generated by create next app",
};

// <meta name="viewport" content="width=device-width, interactive-widget=resizes-content"></meta>
export const viewport: Viewport = {
  width: 'device-width',
  interactiveWidget: 'resizes-content',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* <link
          // 🔔 avoid HMR issues (flash + small clientHeight) when import 'flexlayout-react/style/light.css'
          rel="stylesheet"
          type="text/css"
          href="/css/flexlayout-react__style__light.css"
          as="style"
        /> */}

        {
          // try fix xterm mobile scrolling with keyboard open (Chrome)
          // https://stackoverflow.com/a/74690082/2917822
        }
        <meta name="viewport" content="width=device-width, interactive-widget=resizes-content"></meta>
      </head>
      <body>
        <Root>
          {children}
        </Root>
      </body>
    </html>
  );
}
