import type { Metadata } from "next";

import "@fortawesome/fontawesome-svg-core/styles.css";
import "@xterm/xterm/css/xterm.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "NPC CLI",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          // 🔔 avoid HMR issues (flash + small clientHeight) when import 'flexlayout-react/style/light.css'
          rel="stylesheet"
          type="text/css"
          href="/css/flexlayout-react__style__light.css"
          as="style"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
